[package]
name = "somo"
version = "1.1.0"
edition = "2021"
authors = ["theopfr"]
description = "A human-friendly alternative to netstat for socket and port monitoring on Linux and macOS."
license = "MIT"
readme = "./README.md"
repository = "https://github.com/theopfr/somo/"
keywords = ["netstat", "socket-monitoring", "port-checker"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
clap_complete = "4.5.57"
inquire = "0.7.5"
termimad = "0.33.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.142"
handlebars = "6.3.2"
nix = {version = "0.30.1", features = ["process", "signal"]}
etcetera = "0.10.0"


tempfile = "3.21.0"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.17.0"

[target.'cfg(target_os = "macos")'.dependencies]
netstat2 = "0.11.2"
libproc = "0.14.10"
